/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RockPaperScissorsAbi } from "./RockPaperScissorsAbi";
export * as factories from "./factories";
export { RockPaperScissorsAbi__factory } from "./factories/RockPaperScissorsAbi__factory";
